#!/usr/bin/env python3
"""
Generate a loudly-failing stub for every exported symbol that is not yet
implemented.

This is what makes the port incremental. From the first commit the
library exports all 218 names the reference does, so it loads and
resolves against any consumer; every call that is not yet implemented
aborts with a message naming the symbol rather than silently returning
garbage. Each phase moves names from `symbols.txt` into
`implemented.txt` and the stub disappears.

Getting that bookkeeping wrong is a build failure, not a subtle bug: a
name listed as implemented that is not produces an undefined symbol at
link time, and one left here after being implemented produces a
duplicate symbol.

The signatures come from the vendored BlueZ headers, so each stub is
type-checked against the declaration it satisfies.

Usage:
    scripts/gen_stubs.py [output.c]

Defaults to Sources/CBluetoothLinuxABI/gen/cbt_stubs.c.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INCLUDE = os.path.join(
    ROOT, "Sources", "CBluetoothLinuxABI", "include", "bluetooth"
)
SYMBOLS = os.path.join(ROOT, "scripts", "symbols.txt")
IMPLEMENTED = os.path.join(ROOT, "scripts", "implemented.txt")
DEFAULT_OUTPUT = os.path.join(
    ROOT, "Sources", "CBluetoothLinuxABI", "gen", "cbt_stubs.c"
)

HEADERS = [
    "bluetooth.h",
    "hci.h",
    "hci_lib.h",
    "sdp.h",
    "sdp_lib.h",
]

PROLOGUE = '''/*
 * Generated by scripts/gen_stubs.py — do not edit.
 *
 * One stub per exported symbol that PureSwift has not implemented yet.
 * Each aborts with the symbol name, so an unported call site is
 * immediately identifiable rather than silently wrong.
 *
 * Regenerate after editing scripts/implemented.txt:
 *     scripts/gen_stubs.py
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>
#include <sys/socket.h>

#include <bluetooth/bluetooth.h>
#include <bluetooth/hci.h>
#include <bluetooth/hci_lib.h>
#include <bluetooth/sdp.h>
#include <bluetooth/sdp_lib.h>

__attribute__((noreturn))
static void cbt_unimplemented(const char *symbol)
{
\tfprintf(stderr,
\t\t"libbluetooth (PureSwift): %s is not implemented yet.\\n",
\t\tsymbol);
\tabort();
}

'''


def read_list(path):
    names = []
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            line = line.split("#", 1)[0].strip()
            if line:
                names.append(line)
    return names


def read_declarations():
    """Map symbol name -> (return type, parameter list) from the headers."""
    text = []
    for name in HEADERS:
        path = os.path.join(INCLUDE, name)
        with open(path, encoding="utf-8") as handle:
            text.append(handle.read())
    source = "\n".join(text)

    # Strip comments so a declaration inside one is not picked up.
    source = re.sub(r"/\*.*?\*/", " ", source, flags=re.DOTALL)
    source = re.sub(r"//[^\n]*", " ", source)

    declarations = {}
    # A non-static, non-inline function declaration ending in `;`.
    pattern = re.compile(
        r"(?<![\w])"
        r"((?:const\s+|unsigned\s+|struct\s+|signed\s+)*[A-Za-z_]\w*\s*\**)\s*"
        r"([A-Za-z_]\w*)\s*"
        r"\(([^;{)]*(?:\([^)]*\)[^;{)]*)*)\)\s*;",
        re.MULTILINE,
    )
    for match in pattern.finditer(source):
        return_type, name, parameters = match.groups()
        return_type = " ".join(return_type.split())
        parameters = " ".join(parameters.split()) or "void"
        if return_type in ("return", "typedef", "else", "static", "inline"):
            continue
        declarations[name] = (return_type, parameters)
    return declarations


def stub_body(name, return_type):
    lines = ["\tcbt_unimplemented(\"%s\");" % name]
    return "\n".join(lines)


def main():
    output_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_OUTPUT

    exported = read_list(SYMBOLS)
    implemented = set(read_list(IMPLEMENTED))
    declarations = read_declarations()

    todo = [name for name in exported if name not in implemented]

    chunks = [PROLOGUE]
    missing = []
    for name in todo:
        declaration = declarations.get(name)
        if declaration is None:
            missing.append(name)
            continue
        return_type, parameters = declaration
        separator = "" if return_type.endswith("*") else " "
        chunks.append(
            "%s%s%s(%s)\n{\n%s\n}\n\n"
            % (return_type, separator, name, parameters, stub_body(name, return_type))
        )

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as handle:
        handle.write("".join(chunks))

    print(
        "wrote %s (%d stubs, %d implemented, %d exported)"
        % (
            os.path.relpath(output_path, ROOT),
            len(todo) - len(missing),
            len(implemented),
            len(exported),
        )
    )

    if missing:
        # A symbol the reference exports but no public header declares
        # cannot be stubbed with a checked signature. Report rather than
        # guess: an unchecked stub would defeat the point of vendoring
        # the headers.
        print(
            "error: %d exported symbol(s) have no declaration in the "
            "vendored headers:" % len(missing),
            file=sys.stderr,
        )
        for name in missing:
            print("  %s" % name, file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
