#!/usr/bin/env python3
"""
Generate the linker version script from symbols.txt.

Upstream libbluetooth exports every symbol it defines and carries no
version script. We pin the list instead, so that the Swift runtime's
symbols and our own internals stay local and the export surface is
asserted rather than incidental.

That is new behavior relative to the reference, and the risk it carries
is real: a consumer bound to something incidental that upstream happened
to export would stop resolving. Before this list is treated as final,
Debian's Contents index should be scanned for binaries with an undefined
symbol satisfied by libbluetooth.so.3.

The `bt_uuid_*` family is added on top of symbols.txt: the reference
keeps those in libbluetooth-internal.a and exports none of them, but
PureSwift implements them and there is no reason to hide them.

Usage:
    scripts/gen_symbols.py [output.map]

Defaults to cmake/libbluetooth.map.
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SYMBOLS = os.path.join(ROOT, "scripts", "symbols.txt")
DEFAULT_OUTPUT = os.path.join(ROOT, "cmake", "libbluetooth.map")

# The flat list of everything the version script exports, for
# scripts/check-exports.sh to assert the built library against.
EXPORTED = os.path.join(ROOT, "scripts", "exported.txt")

# Implemented by PureSwift/Bluetooth and exported deliberately, though
# the reference library does not export them.
EXTRA_SYMBOLS = [
    "bt_string_to_uuid",
    "bt_uuid128_create",
    "bt_uuid16_cmp",
    "bt_uuid16_create",
    "bt_uuid32_create",
    "bt_uuid_cmp",
    "bt_uuid_strcmp",
    "bt_uuid_to_le",
    "bt_uuid_to_string",
    "bt_uuid_to_uuid128",
]

VERSION_NODE = "LIBBLUETOOTH_5"


def read_list(path):
    names = []
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            line = line.split("#", 1)[0].strip()
            if line:
                names.append(line)
    return names


def main():
    output_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_OUTPUT

    exported = read_list(SYMBOLS)
    extra = [name for name in EXTRA_SYMBOLS if name not in exported]

    lines = [
        "/*",
        " * Generated by scripts/gen_symbols.py — do not edit.",
        " *",
        " * The export surface of libbluetooth.so.3. Regenerate after",
        " * editing scripts/symbols.txt:",
        " *     scripts/gen_symbols.py",
        " */",
        "",
        "%s {" % VERSION_NODE,
        "global:",
        "    /* The reference export surface (%d) */" % len(exported),
    ]
    lines += ["    %s;" % name for name in sorted(exported)]
    lines += [
        "",
        "    /* Implemented by PureSwift but not exported by the reference (%d) */"
        % len(extra),
    ]
    lines += ["    %s;" % name for name in sorted(extra)]
    lines += [
        "",
        "local:",
        "    *;",
        "};",
        "",
    ]

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))

    with open(EXPORTED, "w", encoding="utf-8") as handle:
        handle.write(
            "# Generated by scripts/gen_symbols.py — do not edit.\n"
            "#\n"
            "# Every symbol cmake/libbluetooth.map exports, flat, for\n"
            "# scripts/check-exports.sh.\n"
        )
        handle.write("\n".join(sorted(exported + extra)) + "\n")

    print(
        "wrote %s (%d symbols: %d reference + %d extra)"
        % (
            os.path.relpath(output_path, ROOT),
            len(exported) + len(extra),
            len(exported),
            len(extra),
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
