#!/usr/bin/env python3
"""
Generate Sources/BluetoothLinuxABI/gen/HCITables.swift from BlueZ's
lib/bluetooth/hci.c and lib/bluetooth/hci.h.

The `hci_*tostr`/`hci_strto*` family (plus `lmp_*`/`pal_*`) are all
table lookups over BlueZ's `hci_map` arrays — name/bit-or-value pairs.
Hand-transcribing the largest of these (`commands_map`, 232 entries;
`lmp_features_map`, 8x9 entries) risks a silent transcription error
that would only surface as a wrong string for one specific bit. Since
every entry is mechanical (a literal name and a `#define`d value),
generating them from the vendored source is both faster and exact.

Usage:
    scripts/generate-hci-tables.py <path-to-bluez>/lib/bluetooth/hci.c

`hci.c` itself is not vendored into this repository — only the headers
are (see Sources/CBluetoothLinuxABI/README.md) — so this script takes
the reference source as an argument rather than reading a shipped copy.
Re-run after re-vendoring a newer hci.h from the same BlueZ release and
commit the generated result.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HCI_H = os.path.join(ROOT, "Sources", "CBluetoothLinuxABI", "include", "bluetooth", "hci.h")
OUTPUT = os.path.join(ROOT, "Sources", "BluetoothLinuxABI", "gen", "HCITables.swift")

HEADER = '''//
//  HCITables.swift
//  BluetoothLinux
//
//  Generated by scripts/generate-hci-tables.py — do not edit.
//
//  Source: BlueZ lib/bluetooth/hci.c's `hci_map` tables, with `#define`
//  values resolved against lib/bluetooth/hci.h.
//

'''


def load_defines():
    text = open(HCI_H, encoding="utf-8").read()
    defines = {}

    # `#define NAME value` where value is a simple integer literal
    # (decimal or hex), skipping function-like macros and multi-token
    # expressions.
    for match in re.finditer(
        r"^#define\s+([A-Za-z_][A-Za-z0-9_]*)\s+(0[xX][0-9A-Fa-f]+|\d+)\s*$",
        text,
        re.MULTILINE,
    ):
        name, value = match.groups()
        defines[name] = int(value, 0)

    # `enum { A, B, C };` — unnamed enums with no explicit values, used
    # for the HCI device flag bit positions (hci_test_bit indices, not
    # bitmasks). Comments and blank lines inside the braces are allowed.
    for match in re.finditer(r"enum\s*\{([^}]*)\}\s*;", text, re.DOTALL):
        body = re.sub(r"/\*.*?\*/", "", match.group(1), flags=re.DOTALL)
        names = [n.strip() for n in body.split(",")]
        value = 0
        for name in names:
            if not name or not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
                continue
            defines.setdefault(name, value)
            value += 1

    return defines


def resolve(token, defines):
    token = token.strip()
    if re.fullmatch(r"0[xX][0-9A-Fa-f]+|\d+", token):
        return int(token, 0)
    if token in defines:
        return defines[token]
    raise ValueError("cannot resolve %r" % token)


def extract_map(source, name):
    match = re.search(
        r"static const hci_map %s\[\] = \{(.*?)\n\};" % re.escape(name),
        source,
        re.DOTALL,
    )
    if not match:
        raise ValueError("map not found: %s" % name)
    body = match.group(1)
    entries = re.findall(r'\{\s*"((?:[^"\\]|\\.)*)"\s*,\s*([^}]+?)\s*\}', body)
    return entries


def extract_features_map(source):
    match = re.search(
        r"static const hci_map lmp_features_map\[8\]\[9\] = \{(.*?)\n\};",
        source,
        re.DOTALL,
    )
    body = match.group(1)
    bytes_ = re.findall(r"\{(.*?)\}(?:,|\s*$)", body, re.DOTALL)
    # The outer split also grabs each byte's own `{ ... }` entries as
    # nested matches; re-split more carefully by top-level byte blocks.
    byte_blocks = re.findall(r"\{\s*/\* Byte \d+ \*/(.*?)\n\t\},?", body, re.DOTALL)
    rows = []
    for block in byte_blocks:
        entries = re.findall(r'\{\s*"((?:[^"\\]|\\.)*)"\s*,\s*([^}]+?)\s*\}', block)
        rows.append(entries)
    return rows


def swift_escape(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def format_table(name, entries, defines, comment):
    lines = ["/// %s" % comment]
    lines.append("internal let %s: [(name: String, value: UInt32)] = [" % name)
    for s, v in entries:
        value = resolve(v, defines)
        lines.append('    ("%s", 0x%x),' % (swift_escape(s), value))
    lines.append("]")
    return "\n".join(lines) + "\n\n"


def main():
    if len(sys.argv) != 2:
        print("usage: generate-hci-tables.py <path to lib/bluetooth/hci.c>", file=sys.stderr)
        return 1
    source = open(sys.argv[1], encoding="utf-8").read()
    defines = load_defines()

    chunks = [HEADER]

    tables = [
        ("hciDeviceFlagsMap", "dev_flags_map", "HCI device flags (bit tests)."),
        ("hciPacketTypeMap", "pkt_type_map", "ACL packet types (bitmask)."),
        ("hciSCOPacketTypeMap", "sco_ptype_map", "SCO packet types (bitmask)."),
        ("hciLinkPolicyMap", "link_policy_map", "Link policy settings (bitmask)."),
        ("hciLinkModeMap", "link_mode_map", "Link mode settings (bitmask)."),
        ("hciVersionMap", "ver_map", "Core specification version (exact match)."),
        ("hciPALVersionMap", "pal_map", "802.11 PAL version (exact match)."),
    ]
    for swift_name, c_name, comment in tables:
        entries = extract_map(source, c_name)
        chunks.append(format_table(swift_name, entries, defines, comment))

    commands = extract_map(source, "commands_map")
    chunks.append(
        format_table(
            "hciCommandsMap",
            commands,
            defines,
            "Supported Commands bit -> name (%d entries)." % len(commands),
        )
    )

    feature_rows = extract_features_map(source)
    chunks.append("/// LMP Features page 0, one array per byte (8 bytes x up to 9 bits).\n")
    chunks.append("internal let lmpFeaturesMap: [[(name: String, value: UInt8)]] = [\n")
    for row in feature_rows:
        chunks.append("    [\n")
        for s, v in row:
            value = resolve(v, defines)
            chunks.append('        ("%s", 0x%02x),\n' % (swift_escape(s), value))
        chunks.append("    ],\n")
    chunks.append("]\n")

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write("".join(chunks))

    print(
        "wrote %s (%d command entries, %d feature bytes)"
        % (os.path.relpath(OUTPUT, ROOT), len(commands), len(feature_rows))
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
